# Generated by Django 5.1.5 on 2025-02-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "1st Year"),
                            ("2", "2nd Year"),
                            ("3", "3rd Year"),
                            ("4", "4th Year"),
                        ],
                        max_length=1,
                    ),
                ),
                ("staff_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("answer_file", models.FileField(upload_to="answer_sheets/")),
                ("is_graded", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
