# Generated by Django 5.1.5 on 2025-02-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_answersheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[("CAT 1", "CAT 1"), ("CAT 2", "CAT 2")],
                max_length=10,
                null=True,
            ),
        ),
    ]
