# Generated by Django 5.1.5 on 2025-02-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_answersheet_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "1st Year"),
                            ("2", "2nd Year"),
                            ("3", "3rd Year"),
                            ("4", "4th Year"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("CAT 1", "CAT 1"), ("CAT 2", "CAT 2")], max_length=10
                    ),
                ),
                ("staff_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AnswerSheet",
        ),
    ]
