# Generated by Django 5.1.5 on 2025-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_studentexam_delete_answersheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("CAT 1", "CAT 1"), ("CAT 2", "CAT 2")], max_length=10
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "1st Year"),
                            ("2", "2nd Year"),
                            ("3", "3rd Year"),
                            ("4", "4th Year"),
                        ],
                        max_length=1,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("question_paper", models.FileField(upload_to="question_papers/")),
                ("answer_key", models.FileField(upload_to="answer_keys/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
