# Generated by Django 5.1.5 on 2025-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexam",
            name="is_evaluated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentexam",
            name="ocr_answer_sheet",
            field=models.FileField(
                blank=True, null=True, upload_to="ocr_answer_sheets/"
            ),
        ),
        migrations.AddField(
            model_name="studentexam",
            name="total_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
